### ISSUE TITLE
fill DB with sample Data

### ISSUE THREAD

**Issue by FeBeBe** [refugeehackathon/brain-backend#10]

**Comment by Midnighter** [comment]
I just pushed (f48629e2e58156f3cb8745ae45d0ac0c1f9649a3) the IPython Notebooks into the repository that can partly convert the Google spreadsheets. They generate consistent CSV files that can be imported into the database.

Some problems remain:
1. The categories in the Project-DB table don't match the ones we came up with before.
2. Contact information is left empty for now.
