### ISSUE TITLE
Als Vertreter eines Flüchtlingsprojekts möchte ich mein Projekt im Metabrain eintragen, um allen Interessierten die Informationen dazu bereitzustellen.

### ISSUE THREAD

**Issue by eshnan** [refugeehackathon/brain-backend#18]
- Frontend des MetaBrain
- Formular zur Registrierung der eigenen Projekte, zum Suchen und Rechercherieren (s.u.)
- Mehrsprachigkeit: Felder können in mehreren Sprachen ausgefüllt werden, Englisch ist Pflicht
- Liste der Felder: _ergänzen_

**Comment by Midnighter** [comment]
Frontend.
