### ISSUE TITLE
Als Vertreter eines Flüchtlingsprojekts möchte ich bereits vorhandene Einträge zu meinem Projekt finden, um keine Duplikate zu erzeugen.

### ISSUE THREAD

**Issue by eshnan** [refugeehackathon/brain-backend#19]
- bei der Suche in der DB und bei der “Registrierung” eines neuen Projekts im MetaBrain werden Einträge auf den Namen geprüft, bei großer Ähnlichkeit wird nachgefragt, ob es sich um dasselbe Projekt handelt. Es wird die Möglichkeit angeboten, den Maintainer des Projekts zu kontaktieren.
- wenn keine Treffer weiter zum Registrierungsformular, um das Projekt einzutragen

**Comment by Midnighter** [comment]
Frontend.
