### ISSUE TITLE
Als Vertreter eines Flüchtlingsprojekts möchte ich Projekte recherchieren, um Kooperationen und Content-Austausch zu ermöglichen und nicht dieselbe Idee nochmal umzusetzen.

### ISSUE THREAD

**Issue by eshnan** [refugeehackathon/brain-backend#20]
- Suchformular und Ergebnisliste nach Projekten z.B. zum Zweck der Kooperation.
- Ausgabe der zentralen Informationen zum Projekt, Ansprechpartner und Kontaktmöglichkeit, Content-Beispiele und Lizenzen

**Comment by Midnighter** [comment]
Frontend.
